src/main/java/pl/lsea/skijumping/entity/Human.java
package pl.lsea.skijumping.entity;

import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Temporal;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.SuperBuilder;
import pl.lsea.skijumping.util.Country;

/**
 * Abstract class
 */
@Entity
@SuperBuilder(toBuilder = true)
@Setter
@Getter
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@ToString
@Inheritance(strategy=InheritanceType.TABLE_PER_CLASS)
public abstract class Human implements Serializable {
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    
    /**
     * Example of protected access to field
     */
    @NotNull
    @Size(min = 1, max = 255)
    protected String firstname;
    
    @NotNull
    @Size(min = 1, max = 255)
    protected String lastname;
    
    @NotNull
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    protected Date birthdate;
    
    /**
     * Field using enum "Country"
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    protected Country country;
    
    public String getFormattedBirthdate() {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        
        return format.format(this.birthdate);
    }
    
}

src/main/java/pl/lsea/skijumping/servlet/MainServlet.java
package pl.lsea.skijumping.servlet;

import java.io.IOException;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/")
public class MainServlet extends HttpServlet {

    @Override
    protected void doGet(
            HttpServletRequest req, 
            HttpServletResponse resp
    ) throws ServletException, IOException {
        
        RequestDispatcher requestDispatcher = req.getRequestDispatcher("index.jsp");
        
        requestDispatcher.forward(req, resp);
    }
}

src/main/java/pl/lsea/skijumping/servlet/SkiJumpAddServlet.java
package pl.lsea.skijumping.servlet;

import java.io.IOException;
import java.util.Set;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;
import pl.lsea.skijumping.dao.SkiJumpDao;
import pl.lsea.skijumping.dao.SkiJumperDao;
import pl.lsea.skijumping.entity.SkiJump;
import pl.lsea.skijumping.util.Country;

@WebServlet("/skijump/add")
public class SkiJumpAddServlet extends HttpServlet {
 
    private SkiJumpDao dao;
    
    private SkiJumperDao udao;

    @Override
    public void init() throws ServletException {
        dao = new SkiJumpDao();
        udao = new SkiJumperDao();
    }

    @Override
    protected void doGet(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {
        req.setAttribute("countries", Country.values());
        req.setAttribute("skiJumpers", udao.findAll());
        
        RequestDispatcher requestDispatcher = req.getRequestDispatcher("../skijump.jsp");

        requestDispatcher.forward(req, resp);
    }
    
    @Override
    protected void doPost(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {
        String constructionPoint = req.getParameter("constructionPoint");
        String worldRecord = req.getParameter("worldRecord");
        
        if(constructionPoint.isEmpty()) {
            constructionPoint = "0";
        }
        
        if(worldRecord.isEmpty()) {
            worldRecord = "0";
        }
        
        SkiJump skiJump = SkiJump
                            .builder()
                            .name(req.getParameter("name"))
                            .description(req.getParameter("description"))
                            .country(Country.valueOf(req.getParameter("country")))
                            .constructionPoint(Double.parseDouble(constructionPoint))
                            .worldRecord(Double.parseDouble(worldRecord))
                            .recordist(udao.findById(Long.parseLong(req.getParameter("recordist"))))
                            .build();
        
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();
        
        Set<ConstraintViolation<SkiJump>> errors = validator.validate(skiJump);

        if(errors.size() > 0) {
            req.setAttribute("errors", errors);
            req.setAttribute("countries", Country.values());
            req.setAttribute("skiJumpers", udao.findAll());
            
            RequestDispatcher requestDispatcher = req.getRequestDispatcher("../skijump.jsp");
            requestDispatcher.forward(req, resp);
        } else {
            dao.save(skiJump);
        
            resp.sendRedirect(req.getContextPath() + "/skijumps");
        }
    }  
}

src/main/java/pl/lsea/skijumping/servlet/SkiJumpDeleteServlet.java
package pl.lsea.skijumping.servlet;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import pl.lsea.skijumping.dao.SkiJumpDao;

@WebServlet("/skijump/delete")
public class SkiJumpDeleteServlet extends HttpServlet {
    
    private SkiJumpDao dao;

    @Override
    public void init() throws ServletException {
        dao = new SkiJumpDao();
    }

    @Override
    protected void doPost(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {
        Long id = Long.parseLong(req.getParameter("id"));
        dao.deleteById(id);
        
        resp.sendRedirect(req.getContextPath() + "/skijumps");
    }
}

src/main/java/pl/lsea/skijumping/servlet/SkiJumpEditServlet.java
package pl.lsea.skijumping.servlet;

import java.io.IOException;
import java.util.Set;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;
import pl.lsea.skijumping.dao.SkiJumpDao;
import pl.lsea.skijumping.dao.SkiJumperDao;
import pl.lsea.skijumping.entity.SkiJump;
import pl.lsea.skijumping.util.Country;

@WebServlet("/skijump/edit")
public class SkiJumpEditServlet extends HttpServlet {

    private SkiJumpDao dao;

    private SkiJumperDao udao;

    @Override
    public void init() throws ServletException {
        dao = new SkiJumpDao();
        udao = new SkiJumperDao();
    }

    @Override
    protected void doGet(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {
        req.setAttribute("countries", Country.values());
        req.setAttribute("skiJumpers", udao.findAll());
        req.setAttribute("item", dao.findById(Long.parseLong(req.getParameter("id"))));

        RequestDispatcher requestDispatcher = req.getRequestDispatcher("../skijump.jsp");

        requestDispatcher.forward(req, resp);
    }

    @Override
    protected void doPost(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {
        SkiJump skiJump = dao.findById(Long.parseLong(req.getParameter("id")));
        String constructionPoint = req.getParameter("constructionPoint");
        String worldRecord = req.getParameter("worldRecord");
        
        if(constructionPoint.isEmpty()) {
            constructionPoint = "0";
        }
        
        if(worldRecord.isEmpty()) {
            worldRecord = "0";
        }
        
        skiJump = skiJump
                .toBuilder()
                .name(req.getParameter("name"))
                .description(req.getParameter("description"))
                .country(Country.valueOf(req.getParameter("country")))
                .constructionPoint(Double.parseDouble(constructionPoint))
                .worldRecord(Double.parseDouble(worldRecord))
                .recordist(udao.findById(Long.parseLong(req.getParameter("recordist"))))
                .build();

        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();
        
        Set<ConstraintViolation<SkiJump>> errors = validator.validate(skiJump);
        
        if(errors.size() > 0) {
            req.setAttribute("errors", errors);
            req.setAttribute("countries", Country.values());
            req.setAttribute("skiJumpers", udao.findAll());
            req.setAttribute("item", dao.findById(Long.parseLong(req.getParameter("id"))));
            
            RequestDispatcher requestDispatcher = req.getRequestDispatcher("../skijump.jsp");
            requestDispatcher.forward(req, resp);
        } else {
            dao.save(skiJump);

            resp.sendRedirect(req.getContextPath() + "/skijumps");
        }
    }
}

src/main/java/pl/lsea/skijumping/servlet/SkiJumperAddServlet.java
package pl.lsea.skijumping.servlet;

import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Set;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.ConstraintViolation;
import javax.validation.Validation;
import javax.validation.Validator;
import javax.validation.ValidatorFactory;
import pl.lsea.skijumping.dao.SkiJumperDao;
import pl.lsea.skijumping.dao.TrainerDao;
import pl.lsea.skijumping.entity.SkiJumper;
import pl.lsea.skijumping.util.Country;

@WebServlet("/skijumper/add")
public class SkiJumperAddServlet extends HttpServlet {
 
    private SkiJumperDao dao;
    
    private TrainerDao udao;

    @Override
    public void init() throws ServletException {
        dao = new SkiJumperDao();
        udao = new TrainerDao();
    }

    @Override
    protected void doGet(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {
        req.setAttribute("countries", Country.values());
        req.setAttribute("trainers", udao.findAll());
        
        RequestDispatcher requestDispatcher = req.getRequestDispatcher("../skijumper.jsp");

        requestDispatcher.forward(req, resp);
    }
    
    @Override
    protected void doPost(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date birthdate;
        try {
            birthdate = format.parse(req.getParameter("birthdate"));
        } catch (ParseException ex) {
            birthdate = new Date();
        }
        
        String height = req.getParameter("height");
        String weight = req.getParameter("weight");
        String privateRecord = req.getParameter("privateRecord");
        String trainerId = req.getParameter("trainer");
        
        if(height.isEmpty()) {
            height = "0";
        }
        
        if(weight.isEmpty()) {
            weight = "0";
        }
        
        if(privateRecord.isEmpty()) {
            privateRecord = "0";
        }
        
        if(trainerId.isEmpty()) {
            trainerId = "0";
        }
        
        SkiJumper skiJumper = SkiJumper
                            .builder()
                            .firstname(req.getParameter("firstname"))
                            .lastname(req.getParameter("lastname"))
                            .birthdate(birthdate)
                            .country(Country.valueOf(req.getParameter("country")))
                            .height(Double.parseDouble(height))
                            .weight(Double.parseDouble(weight))
                            .privateRecord(Double.parseDouble(privateRecord))
                            .trainer(udao.findById(Long.parseLong(trainerId)))
                            .build();
        
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        Validator validator = factory.getValidator();
        
        Set<ConstraintViolation<SkiJumper>> errors = validator.validate(skiJumper);
        
        if(errors.size() > 0) {
            req.setAttribute("errors", errors);
            req.setAttribute("countries", Country.values());
            req.setAttribute("trainers", udao.findAll());
            
            RequestDispatcher requestDispatcher = req.getRequestDispatcher("../skijumper.jsp");
            requestDispatcher.forward(req, resp);
        } else {
            dao.save(skiJumper);
        
            resp.sendRedirect(req.getContextPath() + "/skijumpers");
        }
    }  
}

src/main/java/pl/lsea/skijumping/servlet/SkiJumperDeleteServlet.java
package pl.lsea.skijumping.servlet;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import pl.lsea.skijumping.dao.SkiJumperDao;

@WebServlet("/skijumper/delete")
public class SkiJumperDeleteServlet extends HttpServlet {
    
    private SkiJumperDao dao;

    @Override
    public void init() throws ServletException {
        dao = new SkiJumperDao();
    }

    @Override
    protected void doPost(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {
        Long id = Long.parseLong(req.getParameter("id"));
        dao.deleteById(id);
        
        resp.sendRedirect(req.getContextPath() + "/skijumpers");
    }
}

src/main/java/pl/lsea/skijumping/servlet/SkiJumpersServlet.java
package pl.lsea.skijumping.servlet;

import java.io.IOException;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import pl.lsea.skijumping.dao.SkiJumperDao;

@WebServlet("/skijumpers")
public class SkiJumpersServlet extends HttpServlet {
    
    private SkiJumperDao dao;

    @Override
    public void init() throws ServletException {
        dao = new SkiJumperDao();
    }
    
    @Override
    protected void doGet(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {        
        req.setAttribute("items", dao.findAll());
        
        RequestDispatcher requestDispatcher = req.getRequestDispatcher("skijumpers.jsp");

        requestDispatcher.forward(req, resp);
    }
    
    @Override
    protected void doPost(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {
        
    }
}

src/main/java/pl/lsea/skijumping/servlet/SkiJumpsServlet.java
package pl.lsea.skijumping.servlet;

import java.io.IOException;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import pl.lsea.skijumping.dao.SkiJumpDao;

@WebServlet("/skijumps")
public class SkiJumpsServlet extends HttpServlet {

    private SkiJumpDao dao;

    @Override
    public void init() throws ServletException {
        dao = new SkiJumpDao();
    }
    
    @Override
    protected void doGet(
            HttpServletRequest req,
            HttpServletResponse resp
    ) throws ServletException, IOException {        
        req.setAttribute("items", dao.findAll());
        
        RequestDispatcher requestDispatcher = req.getRequestDispatcher("skijumps.jsp");

        requestDispatcher.forward(req, resp);
    } 
}

src/main/webapp/index.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <title>LSEA 11</title>
    </head>
    <body>
        <div class='container'>
            <h1>Hello World!</h1>
            
            <ul>
                <li><a href='/togetheree/skijumpers'>SkiJumpers</a></li>
                <li><a href='/togetheree/skijumps'>SkiJumps</a></li>
                <li><a href='/togetheree/trainers'>Trainers</a></li>
                <li><a href='/togetheree/skijumps-list.jsp'>SkiJumps List - EJB Session</a></li>
                <li><a href='/togetheree/skijumpers-list.jsp'>SkiJumpers List - EJB Session</a></li>
            </ul>
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

src/main/webapp/skijumper.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <title>LSEA 10</title>
    </head>
    <body>
        <div class='container'>
            <h1>${item != null ? "Edit" : "Add"} SkiJumper ${item.id}</h1>
            
            <form method='POST'>
                <div class="mb-3">
                    <label class='form-label' for='firstname'>First Name</label>
                    <input
                        type='text'
                        name='firstname'
                        id='firstname'
                        class='form-control'
                        value='${item.firstname}'
                    />
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'firstname'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>
                </div>
                
                <div class="mb-3">
                    <label class='form-label' for='lastname'>Last Name</label>
                    <input
                        type='text'
                        name='lastname'
                        id='lastname'
                        class='form-control'
                        value='${item.lastname}'
                    />
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'lastname'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>
                </div>
                
                <div class="mb-3">
                    <label class='form-label' for='country'>Country</label>
                    <select
                        name='country'
                        id='country'
                        class='form-control'
                    >
                        <c:forEach items="${countries}" var="country">
                            <option ${country == item.country ? 'selected="selected"' : ''} value='${country}'>${country}</option>
                        </c:forEach>
                    </select>
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'country'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>
                </div>
                
                <div class="mb-3">
                    <label class='form-label' for='birthdate'>Birthdate</label>
                    <input
                        type='date'
                        name='birthdate'
                        id='birthdate'
                        class='form-control'
                        value='${item.formattedBirthdate}'
                    />
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'birthdate'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>                    
                </div>
                
                <div class="mb-3">
                    <label class='form-label' for='height'>Height</label>
                    <input
                        type='number'
                        step='0.1'
                        name='height'
                        id='height'
                        class='form-control'
                        value='${item.height}'
                    />
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'height'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>                    
                </div>
                
                <div class="mb-3">
                    <label class='form-label' for='weight'>Weight</label>
                    <input
                        type='number'
                        step='0.1'
                        name='weight'
                        id='weight'
                        class='form-control'
                        value='${item.weight}'
                    />
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'weight'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>
                </div>
                
                <div class="mb-3">
                    <label class='form-label' for='privateRecord'>Private Record</label>
                    <input
                        type='number'
                        step='0.1'
                        name='privateRecord'
                        id='privateRecord'
                        class='form-control'
                        value='${item.privateRecord}'
                    />
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'privateRecord'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>
                </div>
                
                <div class="mb-3">
                    <label class='form-label' for='trainer'>Trainer</label>
                    <select
                        name='trainer'
                        id='trainer'
                        class='form-control'
                    >
                        <option value=''>None</option>
                        <c:forEach items="${trainers}" var="trainer">
                            <option ${trainer.id == item.trainer.id ? 'selected="selected"' : ''} value='${trainer.id}'>${trainer.firstname} ${trainer.lastname}</option>
                        </c:forEach>
                    </select>
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'trainer'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>
                </div>
                
                <button type='submit' class='btn btn-primary'>Save</button>
            </form>
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>

src/main/webapp/trainer.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <title>LSEA 10</title>
    </head>
    <body>
        <div class='container'>
            <h1>${item != null ? "Edit" : "Add"} Trainer ${item.id}</h1>
            
            <form method='POST'>
                <div class="mb-3">
                    <label class='form-label' for='firstname'>First Name</label>
                    <input
                        type='text'
                        name='firstname'
                        id='firstname'
                        class='form-control'
                        value='${item.firstname}'
                    />
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'firstname'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>
                </div>
                
                <div class="mb-3">
                    <label class='form-label' for='lastname'>Last Name</label>
                    <input
                        type='text'
                        name='lastname'
                        id='lastname'
                        class='form-control'
                        value='${item.lastname}'
                    />
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'lastname'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>
                </div>
                
                <div class="mb-3">
                    <label class='form-label' for='country'>Country</label>
                    <select
                        name='country'
                        id='country'
                        class='form-control'
                    >
                        <c:forEach items="${countries}" var="country">
                            <option ${country == item.country ? 'selected="selected"' : ''} value='${country}'>${country}</option>
                        </c:forEach>
                    </select>
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'country'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>
                </div>
                    
                <div class="mb-3">
                    <label class='form-label' for='birthdate'>Birthdate</label>
                    <input
                        type='date'
                        name='birthdate'
                        id='birthdate'
                        class='form-control'
                        value="${item.formattedBirthdate}"
                    /> 
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'birthdate'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>  
                </div>
                
                <div class="mb-3">
                    <label class='form-label' for='representation'>Representation</label>
                    <input
                        type='text'
                        name='representation'
                        id='representation'
                        class='form-control'
                        value='${item.representation}'
                    />
                    <ul>
                        <c:forEach items="${errors}" var="error">
                            <c:if test="${error.getPropertyPath() == 'representation'}">
                                <li>${error.getMessage()}</li>
                            </c:if>
                        </c:forEach>
                    </ul>  
                </div>
                
                <button type='submit' class='btn btn-primary'>Save</button>
            </form>
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    </body>
</html>